
#type: args

train:
  epochs: 400
  batch_size: 32
  lr: 0.0005

diffusion:
  layers: 4 #4 
  channels: 64 
  nheads: 1 #8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 100
  schedule: "quad"

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "random"
